import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.sqldelight)
}

// IGDB credentials come from local.properties (gitignored) or environment variables,
// never committed to source control. See local.properties for the expected keys.
val secretsProperties = Properties().apply {
    val localPropertiesFile = rootProject.file("local.properties")
    if (localPropertiesFile.exists()) {
        localPropertiesFile.inputStream().use { load(it) }
    }
}

fun igdbSecret(key: String): String =
    secretsProperties.getProperty(key) ?: System.getenv(key) ?: ""

val generateIgdbSecrets = tasks.register("generateIgdbSecrets") {
    val outputDir = layout.buildDirectory.dir("generated/igdbSecrets/kotlin")
    val clientId = igdbSecret("IGDB_CLIENT_ID")
    val clientSecret = igdbSecret("IGDB_CLIENT_SECRET")
    outputs.dir(outputDir)
    doLast {
        val packageDir = outputDir.get().dir("com/obsidian/shipathon/data/remote/igdb").asFile
        packageDir.mkdirs()
        File(packageDir, "IgdbSecrets.kt").writeText(
            """
            |package com.obsidian.shipathon.data.remote.igdb
            |
            |// Generated by the generateIgdbSecrets Gradle task from local.properties. Do not edit or commit.
            |internal object IgdbSecrets {
            |    const val CLIENT_ID: String = "$clientId"
            |    const val CLIENT_SECRET: String = "$clientSecret"
            |}
            |
            """.trimMargin()
        )
    }
}

kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
            binaryOption("bundleId", "com.obsidian.shipathon.shared")
        }
    }
    
    js {
        browser()
    }
    
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }
    
    android {
        namespace = "com.obsidian.shipathon.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.compose.uiTooling)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.sqldelight.android.driver)
            implementation(libs.androidx.activity.compose)
        }
        commonMain {
            kotlin.srcDir(generateIgdbSecrets)
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.ui)
                implementation(libs.compose.components.resources)
                implementation(libs.compose.uiToolingPreview)
                implementation(libs.androidx.lifecycle.viewmodelCompose)
                implementation(libs.androidx.lifecycle.runtimeCompose)
                implementation(libs.kotlinx.datetime)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
                implementation(libs.ktor.client.logging)
                implementation(libs.coil.compose)
                implementation(libs.coil.network.ktor)
                implementation(libs.sqldelight.runtime)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
            implementation(libs.sqldelight.native.driver)
        }
        jsMain.dependencies {
            implementation(libs.wrappers.browser)
        }
    }
}

sqldelight {
    databases {
        create("ObsidianDatabase") {
            packageName.set("com.obsidian.shipathon.data.local.db")
        }
    }
}